services:
  android:
    image: redroid/redroid:11.0.0-latest
    container_name: stend-android
    privileged: true
    ports:
      - "5555:5555"
    volumes:
      - ./data:/data
    restart: always
    command: androidboot.redroid_width=720 androidboot.redroid_height=1280 androidboot.redroid_dpi=320
